---
title: "Workshop 4: Practice Problems"
author: "Calvin J. Munson"
date: "May 7th, 2020"
output: html_document
---

<br>

***

<br>

Hi everyone!

This document contains 10 practice problems meant to help you work through some of the functions and concepts we have learned thus far in the workshop series. We will be using the "animal_weight.csv" file that I sent through email (or visit Workshop 4's folder in the Google Drive). Please download it and store it wherever you have been storing the rest of your data. 

If you get stuck or want to check your answers, you may check out the other document I sent, which contains potential solutions to each question! However, I recommend Googling specific concepts first :)

Good luck! Feel free to email me with any questions. I hope the worksheet ends up being helpful

-Calvin

<br>

***

<br>

## Questions:

<br>

#### 1. Set your working directory to whatever folder you are storing the data in, and read in the tidyverse packages from the library

<br>

<br>

***

<br>

#### 2. Read in the .csv file called "animal_weight.csv" and store it in as data object called animal_weights. 
After you have read in the file, write code to: a) Look at the header of the data, b) find the number of columns in the data, and c) find the number of rows in the data

<br>

<br>

***

<br>

#### 3. Identify the unique species and unique age classes present in the dataset

<br>

<br>



<br>

***

<br>

#### 4. Write code to calculate the mean weight of each species in the dataset

Hint: group_by() and summarise() are your friends

<br>

<br>

***

<br>

#### 5. Calculate the same average weight, but this time for each species/age class combination in the dataset (for instance, what does the average elephant child weight? Elephant adult? Hippo child? etc)

<br>

<br>

***

<br>

#### 6. Next, calculate both mean weight AND mean height in the same data frame for each species/age class combination

<br>

<br>

***

<br>

#### 7. You may have noticed that there is also a column for the sex of the animal, but that the data only exists for the Hippos in our dataset. Create a new dataframe called hippo_stats, which a) only includes data from Hippos, and b) has the mean weight and height for each species, sex, and age combination in the dataset.

<br>


<br>

***

<br>

#### 8. Calculate Body Mass Index (BMI) for each individual animal

In humans, BMI is calculated as:

$$BMI = kg/m^{2}$$

Where BMI is body mass index, kg is mass in kilograms, and m is height in meters.

Taking the original dataframe, create a new column that contains a calculated BMI for each individual animal (this is obviously totally meaningless in terms of actual data on these species!)

Hint: mutate() is your friend! Also, if you are stuck on how to square a value in R, check out our even better friend, Google!


<br>

***

<br>

#### 9. Using ggplot, create a set of boxplots showing the distribution of weights for each species

Hint: Think about what value you want on which axis

<br>

<br>

***

<br>

#### 10. Create a more detailed boxplot, this time including the fill of the boxplot as the age class of the species

Additionally, change a few of the features of the plot:

a) Add neat x and y axis labels
b) Add a plot title
c) Change the y-axis limits to include 0 as a minimum

Hint: Again, use Google if you're stuck on how to change these features. The website Stack Overflow is a great place to go.

<br>

<br>

***

<br>


